### ISSUE TITLE
Stim & Gas Grenades not functioning properly*

### ISSUE THREAD

**Issue by ColonelRedips** [CurlySparkle/ARC9_Cod2019_Shared#12]
(*I only tested this in singleplayer, so take this with a grain of salt. Also gas grenades only stun NPCs)

Stim / Gas grenade atts for UBGLs, Gas Grenades, and the MGL-32 seemingly do not have damage / healing properties assigned to them.

**Comment by CurlySparkle** [comment]
Weird, i checked in singleplayer as well and so far both normal gas and heal gas work fine on my side 🤷🏻‍♀️

**Comment by ColonelRedips** [comment]
You're correct. Fake Hits Fix https://steamcommunity.com/sharedfiles/filedetails/?id=2569993674 messes with the code. I'd suggest writing it down as part of a list of incompatible addons.
